### ISSUE TITLE
Reproduced results on imagenet-subset

### ISSUE THREAD

**Issue by solucky-95** [yulu0724/SDC-IL#12]
Hello,

Thank you for your time.
You have provided two pre-trained models for cifar100 and imagenet-subset respectively. The cifar100 one can perfectly reproduce your results, but the results from the imagenet-subset one are quite low (for task 0, it only gets 30%-40%). Are you using the first 100 classes of the original imagenet or applying random seed 1993 and then selecting the first 100 classes? I have tried both but the results are not good. From my understanding, the starting point (task 0) should produce the same results using your pre-trained model.

Best.

**Comment by JoyHuYY1412** [comment]
> Hello,
> 
> Thank you for your time.
> You have provided two pre-trained models for cifar100 and imagenet-subset respectively. The cifar100 one can perfectly reproduce your results, but the results from the imagenet-subset one are quite low (for task 0, it only gets 30%-40%). Are you using the first 100 classes of the original imagenet or applying random seed 1993 and then selecting the first 100 classes? I have tried both but the results are not good. From my understanding, the starting point (task 0) should produce the same results using your pre-trained model.
> 
> Best.

Hi, would you please share your results on CIFAR? Since there is no accurate value in the original paper, is would be really nice to have your results.

**Comment by AvivSham** [comment]
Hi @solucky-95 !
Did you find the reason for the poor performance on Mini-Imagenet dataset?  If yes it would be great if you can share what was the problem and how did you solve it. 

@yulu0724  May you help and provide some detailed instructions on how to reproduce the results for Mini-Imagenet dataset?
