### ISSUE TITLE
The SDC function

### ISSUE THREAD

**Issue by Vitvicky** [yulu0724/SDC-IL#5]
Hi, yulu

Thanks so much for your shared code and work, it is very impressive. I see the Implementation Details of the paper, and find that in the runDemo.sh, "method" not include SDC function. I also do not find this function in the code. Is it missed in the current version? 

Thanks

**Comment by yulu0724** [comment]
Hi,
Thanks for the interest. Our SDC method can be used for many methods including Fine-tuning, LwF, EWC and MAS. We apply SDC during test time. So you can check the test code and choose to use SDC or not. (We save all the training models for test, you can also apply SDC during training without saving the models.)

**Comment by sega-hsj** [comment]
What part of the code do I need to change, if I want to use the SDC function?
