### ISSUE TITLE
Model Saving During Training

### ISSUE THREAD

**Issue by akashgokul** [yulu0724/SDC-IL#9]
[Here](https://github.com/yulu0724/SDC-IL/blob/master/train.py#L239) you save models every n epochs (e.g. 50). However, that seems to break [this](https://github.com/yulu0724/SDC-IL/blob/master/train.py#L156) line because the last epoch (e.g. epoch 200) is not saved but a retrieval is attempted.

**Comment by yulu0724** [comment]
Usually we set the training epochs for example 201, and save every 50/100/200 epochs, so the last saved model is actually the 200th epoch.
